### ISSUE TITLE
ajouter un footer

### ISSUE THREAD

**Issue by bu7ch** [Mirosz-Mike/nba_app_react#6]
ajouter du composant footer sur la base du composant `Header` : 

<img width="207" alt="capture d ecran 2018-08-27 a 13 17 07" src="https://user-images.githubusercontent.com/2312400/44657006-8e0e7e00-a9fb-11e8-86b4-2f327f488706.png">
 
- [x] faire une branch d'abord comme ça je pourrait valider avant que tu le merge sur le mastrer
- [x] avec au lieu de `2017` j'ai 2018 😄 ( donc gérer de manière dynamique)

**Comment by Mirosz-Mike** [comment]
J'ai push ma parti c'est ça que tu voulais ?

**Comment by bu7ch** [comment]
nickel sauf que tu n'as pas fait de call dynamique tu as écris direct 2018.. moi je veux que sa update automatiquement en fonction de l'année

**Comment by Mirosz-Mike** [comment]
C'est bon pour la date !
