### ISSUE TITLE
installer un nouveau package

### ISSUE THREAD

**Issue by bu7ch** [Mirosz-Mike/nba_app_react#7]
- [x] installer `json-server` sur une nouvelle branche

- [x] configuration de `json-server`

- [x] attendre mon go avant de PR sur le master

**Comment by GeoffreyDu** [comment]
j'ai installé json-server je dois faire une config sur le component SideNav-items.js?

**Comment by bu7ch** [comment]
ok je vais te dire comment faire le reste :)
pour la config... juste je mange en meme temps :)

**Comment by GeoffreyDu** [comment]
mange tranquillement t'inquète, bon app
